LabOOP/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LabOOP.Models
{
    public partial class Order
    {
        public Order()
        {
            Feedbacks = new HashSet<Feedback>();
            ProductsOrders = new HashSet<ProductsOrder>();
        }

        public int Id { get; set; }
        public int? ClientId { get; set; }
        public DateTime? DateOrder { get; set; }

        [Required(ErrorMessage = "Постачальник має бути")]
        public int? DeliverId { get; set; }

        [Required(ErrorMessage = "Адреса має бути")]
        [StringLength(40, MinimumLength = 7)]
        public string? Address { get; set; }

        public virtual Client? Client { get; set; }
        public virtual Deliver? Deliver { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<ProductsOrder> ProductsOrders { get; set; }
    }
}

LabOOP/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LabOOP.Models;
using LabOOP.ViewModels;

namespace LabOOP.Controllers
{
    public class FeedbacksController : Controller
    {
        private readonly DBSHOPContext _context;

        public FeedbacksController(DBSHOPContext context)
        {
            _context = context;
        }

        // GET: Feedbacks
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
                return NotFound();
            ViewBag.orderId = id;
            var dBSHOPContext = _context.Feedbacks.
                Include(f => f.Order).
                Where(e => e.OrderId == id);
            return View(await dBSHOPContext.ToListAsync());
        }

        // GET: Feedbacks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Feedbacks == null)
            {
                return NotFound();
            }

            var feedback = await _context.Feedbacks
                .Include(f => f.Order)
                .FirstOrDefaultAsync(m => m.Id == id);
            ViewBag.orderId = feedback?.OrderId ?? null;
            if (feedback == null)
            {
                return NotFound();
            }

            return View(feedback);
        }

        // GET: Feedbacks/Create
        public IActionResult Create(int? orderId)
        {
            if (orderId == null)
            {
                return NotFound();
            }
            ViewBag.orderId = orderId;
            return View();
        }

        // POST: Feedbacks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? orderId, [Bind("Id,DateOfPublication,OrderId,Description")] Feedback feedback)
        {
            if(orderId == null) { return NotFound(); };
            if (ModelState.IsValid)
            {
                feedback.OrderId = orderId;
                feedback.DateOfPublication = DateTime.Now;
                _context.Add(feedback);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new {id = orderId});
            }
            return View(feedback);
        }

        // GET: Feedbacks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Feedbacks == null)
            {
                return NotFound();
            }

            var feedback = await _context.Feedbacks
                .Include(f => f.Order)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (feedback == null)
            {
                return NotFound();
            }

            return View(feedback);
        }

        // POST: Feedbacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Feedbacks == null)
            {
                return Problem("Entity set 'DBSHOPContext.Feedbacks'  is null.");
            }
            var feedback = await _context.Feedbacks.FindAsync(id);
            int? orderId = null;
            if (feedback != null)
            {
                 orderId = feedback.OrderId;
                _context.Feedbacks.Remove(feedback);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new {id = orderId});
        }

        private bool FeedbackExists(int id)
        {
          return _context.Feedbacks.Any(e => e.Id == id);
        }
    }
}

LabOOP/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LabOOP.Models;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ClosedXML.Excel;
using System.Drawing;
using DocumentFormat.OpenXml.Spreadsheet;
using DocumentFormat.OpenXml.Drawing;
using System.Globalization;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Http;

namespace LabOOP.Controllers
{
    public class OrdersController : Controller
    {
        private readonly DBSHOPContext _context;

        public OrdersController(DBSHOPContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
           var dBSHOPContext = await _context.Orders.Include(o => o.Client).Include(o => o.Deliver).Include(o => o.ProductsOrders).ToListAsync();
           var dBProducts = await _context.ProductsOrders.ToListAsync();
                foreach (var item in dBSHOPContext)
                {             
                        if (item.DateOrder == null)
                        {
                           foreach(var orderproduct in item.ProductsOrders)
                             _context.Remove(orderproduct);
                           _context.Remove(item);
                           await _context.SaveChangesAsync();
                        }                  
                }
            var filteredOrders = await _context.Orders.Include(o => o.Client).Include(o => o.Deliver).ToListAsync();
            return View(filteredOrders);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmPurchase(int orderId)
        {
            var productCount = await _context.ProductsOrders.Where(elem => elem.OrderId == orderId).CountAsync();
            if (productCount > 0)
            {
                var order = await _context.Orders.FirstOrDefaultAsync(elem => elem.Id == orderId);
                if (order == null)
                    return NotFound();
                else
                {
                    order.DateOrder = DateTime.Now;
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }
            var order = await _context.Orders
                .Include(o => o.Client)
                .Include(a => a.ProductsOrders)
                .Include(d => d.Deliver)
                .ThenInclude(b => b.Transport)
                .FirstOrDefaultAsync(m => m.Id == id);

            var productsInOrder = await _context.ProductsOrders.
                Where(elem => elem.OrderId == id).
                Include(o => o.Product).
                ThenInclude(b => b.Country).
                ToListAsync();

            ViewBag.orderId = id;
            if (order == null)
            {
                return NotFound();
            }
            var deliver = order.Deliver;
            ViewBag.Deliver = deliver;
            return View(productsInOrder);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Id");
            ViewData["DeliverId"] = new SelectList(_context.Delivers.Include(o => o.Transport), "Id", "DisplayText");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ClientId,DateOrder,DeliverId,,Address")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction("AddProduct", "Products", new { id = order.Id });
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Id", order.ClientId);
            ViewData["DeliverId"] = new SelectList(_context.Delivers.Include(o => o.Transport), "Id", "Name", order.DeliverId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }
            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Id", order.ClientId);
            ViewData["DeliverId"] = new SelectList(_context.Delivers.Include(o => o.Transport), "Id", "DisplayText", order.DeliverId);
            return View(order);
        }
        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ClientId,DateOrder,DeliverId,Address")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("AddProduct", "Products", new { id = id });
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "Id", order.ClientId);
            ViewData["DeliverId"] = new SelectList(_context.Delivers.Include(o => o.Transport), "Id", "DisplayText", order.DeliverId);
            return View(order);
        }
        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Client)
                .Include(o => o.Deliver)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'DBSHOPContext.Orders'  is null.");
            }
            var order = await _context.Orders
                .Include(o => o.ProductsOrders)
                .Include(o => o.Deliver).Include(o=>o.Feedbacks)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order != null)
            {
                foreach(var o in order.ProductsOrders)
                    _context.Remove(o);
                foreach (var o in order.Feedbacks)
                    _context.Remove(o);
                _context.Orders.Remove(order);
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
          return _context.Orders.Any(e => e.Id == id);
        }

        public ActionResult Export()
        {
            using (XLWorkbook workbook = new XLWorkbook(XLEventTracking.Disabled))
            {
                var delivers = _context.Delivers.
                    Include(e => e.Transport).
                    Include(a => a.Orders)
                    .ThenInclude(b => b.Feedbacks)
                    .ToList();
                var transports = _context.Transports.Include(e => e.Delivers).ThenInclude(a => a.Orders).ThenInclude(f => f.Feedbacks).ToList();
                foreach (var transport in transports)
                {
                    var worksheet = CreareWorkSheet(workbook, transport);
                    CreatePage(worksheet);
                    /* worksheet.Cell("A1").Value = "Номер телефону";
                     worksheet.Cell("B1").Value = "Метод транспорту";
                     worksheet.Cell("C1").Value = "Ім`я";
                     worksheet.Cell("D1").Value = "Фамілія";
                     worksheet.Cell("E1").Value = "Коментар";
                     worksheet.Row(1).Style.Font.Bold = true;*/
                    // var feedback = FindFeedbacks(deliver);
                    ValueInTable(worksheet, transport);
                    /*for (int i = 0; i < books.Count; i++)
                    {
                        worksheet.Cell(i + 2, 1).Value = books[i].Name;
                        worksheet.Cell(i + 2, 7).Value = books[i].Info;
                        var authorBooks = _context.AuthorBooks.Where(ab => ab.BookId == books[i].Id).Include("Author").ToList();
                        int j = 0;
                        foreach (var authorBook in authorBooks)
                        {
                            if (j < 4)
                            {

LabOOP/Views/Orders/BadResult.cshtml
@if (ViewBag.Success != null)
 {
     <div style="font-size: 3em;">@ViewBag.Success</div>
 }
<div class="col-md-12">
    <a href="@Url.Action("Index", "Orders")" class="btn btn-sm btn-info btn mb-2">List Orders</a>
</div>

LabOOP/Views/Orders/Create.cshtml
@model LabOOP.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Веберіть доставщика </h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
             <div class="form-group">
                <label asp-for="Address" class="control-label">Delivery address</label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
             </div>
            <div class="form-group">
                <label asp-for="DeliverId" class="control-label">Deliver Information</label>
                <select asp-for="DeliverId" class="form-control" asp-items="ViewBag.DeliverId" required></select>
                <span asp-validation-for="DeliverId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Choose" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

LabOOP/Views/Orders/Delete.cshtml
@model LabOOP.Models.Order

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LabOOP/Views/Orders/Details.cshtml
@model IEnumerable<LabOOP.Models.ProductsOrder>
@{
    ViewData["Title"] = "ListOfProducts";
    decimal totalPrice = 0;
    decimal IntermediateAmount = 0m;
    int orderId = @ViewBag.orderId;
}
<div>
    <h4>Deliver</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Phone Number:
        </dt>
        <dd class="col-sm-10">
            @ViewBag.Deliver?.PhoneNumber
        </dd>
        <dt class="col-sm-2">
            How to deliver:
        </dt>
        <dd class="col-sm-10">
            @ViewBag.Deliver?.Transport.Name
        </dd>
        <dt class="col-sm-2">
            Name:
        </dt>
        <dd class="col-sm-10">
            @ViewBag.Deliver?.Name
        </dd>
        <dt class="col-sm-2">
            Surname:
        </dt>
        <dd class="col-sm-10">
            @ViewBag.Deliver?.Surname
        </dd>
    </dl>
</div>
 <div class="container">
     <div class="row">
        <div class="col-12">
            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
        </div>
     </div>
  <div class="row mt-3">
    <div class="col-12">
       <h1>List of selected products</h1>
   </div>
  </div>
  <div class="row mt-3">
    <div class="col-12">
      <div class="table-responsive">
       <table class="table table-bordered table-striped">
         <thead class="thead-dark">
           <tr>
             <th scope="col" style="position: sticky; top: 0; z-index: 1;">Product Name</th>
             <th scope="col" style="position: sticky; top: 0; z-index: 1;">Price</th>
             <th scope="col" style="position: sticky; top: 0; z-index: 1;">Description</th>
             <th scope="col" style="position: sticky; top: 0; z-index: 1;">Weight</th>
             <th scope="col" style="position: sticky; top: 0; z-index: 1;">Country</th>
             <th scope="col" style="position: sticky; top: 0; z-index: 1;">Count</th>
             <th scope="col" style="position: sticky; top: 0; z-index: 1;">Total Price</th>
          </tr>
 </thead>
 <tbody>
 @foreach (var item in Model)
  {
    <tr>
      <td>@item.Product.Name</td>
      <td>@item.Product.Price.ToString("C")</td>
      <td>@item.Product.Description</td>
      <td>@item.Product.WeightInKilograms</td>
      <td>@item.Product.Country.Name</td>
      <td>@item.Count</td>
     @{
       IntermediateAmount = item.Count * item.Product.Price;
       totalPrice += IntermediateAmount;
      }
    <td>@IntermediateAmount.ToString("C")</td>
   </tr>
 }
 <tr>
    <td colspan="6" class="text-right font-weight-bold">Total Price:</td>
    <td>@totalPrice.ToString("C")</td>
 </tr>
</tbody>
                </table>
            </div>
        </div>
    </div>
 </div>

@section scripts
    {

    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load("current", { packages: ["corechart"] });
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {
            $.get('/api/Chart/ProductList/@orderId', function (ProductList) {
                var data = google.visualization.arrayToDataTable(ProductList);
                var options = {
                    title: 'Загальна ціна продуктів у замовленні',
                    width: 900,
                    height: 500,
                    legend: { position: 'none' },
                    chartArea: { width: '50%' },
                    hAxis: {
                        title: 'Ціна',
                        minValue: 0
                    },
                    vAxis: {
                        title: 'Назва продукту'
                    }
                };
                var chart = new google.visualization.PieChart(document.getElementById('barchart_values'));
                chart.draw(data, options);
            });
        }
    </script>
}
<div id="barchart_values"></div>

LabOOP/Views/Orders/Edit.cshtml
@model LabOOP.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order change</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @*<div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>*@
           @* <div class="form-group">
                <label asp-for="DateOrder" class="control-label"></label>
                <input asp-for="DateOrder" class="form-control" />
                <span asp-validation-for="DateOrder" class="text-danger"></span>
            </div>*@
             <div class="form-group">
                <label asp-for="Address" class="control-label">Delivery address</label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
             </div>
            <div class="form-group">
                <label asp-for="DeliverId" class="control-label"></label>
                <select asp-for="DeliverId" class="form-control" asp-items="ViewBag.DeliverId"></select>
                <span asp-validation-for="DeliverId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Products" asp-action="AddProduct" asp-route-id="@Model.Id">Back to List</a>
</div>

LabOOP/Views/Orders/Index.cshtml
@model IEnumerable<LabOOP.Models.Order>

@{
    ViewData["Title"] = "Orders";
}
<section>
    <h2>Експорт інформації в файл</h2>
    <form method="post" action="@Url.Action("Export", "Orders")">
        <button type="submit" class="button button--download">
            <i class="fas fa-download"></i> Завантажити дані
        </button>
    </form>
</section>
<div>
    <h3 class="mb-4 text-lg font-medium text-gray-700">Оберіть excel-файл для завантаження</h3>
    @using (Html.BeginForm("Import", "Orders", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
    {
        <div class="mb-4">
            <label for="fileExcel" class="block mb-2 text-sm font-medium text-gray-700">Виберіть файл</label>
            <input type="file" name="fileExcel" id="fileExcel" class="border rounded-md py-2 px-3 text-sm text-gray-700" />
        </div>
        <div>
            <button type="submit" class="px-4 py-2 font-medium text-white bg-blue-500 rounded-md hover:bg-blue-600 transition-colors duration-300">Завантажити</button>
        </div>
    }
</div>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mb-4">Orders</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Create")" class="btn btn-primary mb-3">Create New</a>
        </div>
    </div>
    <div class="row">
       <div class="col-md-12">
          <div class="table-responsive">
               <table class="table table-striped table-bordered">
                   <thead>
                       <tr>
                            <th>Date of created order</th>
                            <th>Delivery address</th>
                            <th>Deliver's Name</th>
                            <th>Deliver's Surname</th>
                            <th>Deliver's' mobile number</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.DateOrder)</td>
                                <td>@Html.DisplayFor(modelItem => item.Address)</td>
                                <td>@Html.DisplayFor(modelItem => item.Deliver.Name)</td>
                                <td>@Html.DisplayFor(modelItem => item.Deliver.Surname)</td>
                                <td>@Html.DisplayFor(modelItem => item.Deliver.PhoneNumber)</td>
                                <td>
                                    <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-sm btn-info">Details</a>
                                    <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-sm btn-danger">Delete</a>
                                    <a href="@Url.Action("Index", "Feedbacks", new { id = item.Id })" class="btn btn-sm btn-success">Comments</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>